### PR TITLE
Added changes for single node deployment

### PR DESCRIPTION
**Pull request by rchikatw**
Handled create volume task for single-node deployment

### CODE REVIEW

**Review by gobindadas — COMMENTED** [review]
LGTM

**Review by gobindadas — APPROVED** [review]
LGTM

**Review by gobindadas — APPROVED** [review]

**Comment by minjong-ha** [comment]
Thank you
You are the great one

**Comment by UXabre** [comment]
When would a new version of gluster-ansible-features package be released, as not having this PR leaves us with a broken hyper-converged single-node setup in oVirt node (which we workaround by manually patching it for now)

**Pull request merged**
